# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Jakarta MVC TCK against a WildFly build

on:
  workflow_dispatch:
    inputs:
      wildfly-branch:
        description: "WildFly Branch/Tag"
        required: true
        default: "main"
        type: string
      wildfly-repo:
        description: "WildFly Repository"
        required: true
        default: "wildfly/wildfly"
        type: string
      wildfly-feature-pack-artifactId:
        description: "WildFly feature pack artifactId"
        required: true
        default: "wildfly-galleon-pack"
        type: string
      jdk-matrix:
        description: "Provide desired JDKs in stringified array format"
        required: true
        default: "['11','17','21']"
      os-matrix:
        description: "Provide desired OSs in stringified array format"
        required: true
        default: "['linux']"

jobs:
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: ${{ inputs.wildfly-branch }}
      wildfly-repo: ${{ inputs.wildfly-repo }}

  tck-run:
   runs-on: ubuntu-latest
   needs: wildfly-build
   name: 'TCK run - SE ${{ matrix.JDK }} on ${{ matrix.OS }}'
   strategy:
     fail-fast: false
     matrix:
       OS: ${{ fromJSON(github.event.inputs.os-matrix) }}
       JDK: ${{ fromJSON(github.event.inputs.jdk-matrix) }}

   steps:
     - uses: actions/checkout@v4
     - uses: actions/download-artifact@v4
       with:
         name: wildfly-maven-repository
         path: .
     - name: Extract Maven Repo
       shell: bash
       run: |
         tar -xzf wildfly-maven-repository.tar.gz -C ~
     - name: Set up JDK ${{ matrix.JDK }}
       uses: actions/setup-java@v4
       with:
         java-version: ${{ matrix.JDK }}
         distribution: 'temurin'
         cache: 'maven'
     - name: Run TCK on ${{ matrix.OS }} with Java ${{ matrix.JDK }} using WildFly ${{ needs.wildfly-build.outputs.wildfly-version }}
       run: mvn -B -ntp clean verify -pl testsuite/tck -Dkrazo.feature.pack.artifactId=${{ inputs.wildfly-feature-pack-artifactId }} -Dkrazo.feature.pack.version=${{ needs.wildfly-build.outputs.wildfly-version }}
